apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-viewer-database
  namespace: media-viewer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn
